DEVICE_PATH := device/samsung/gts10uwifi

# Kernel
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/Image.gz-dtb
BOARD_KERNEL_IMAGE_NAME := Image.gz-dtb
BOARD_KERNEL_BASE := 0x3fff8000
BOARD_KERNEL_PAGESIZE := 4096
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2 loop.max_part=7
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x26f08000
BOARD_TAGS_OFFSET := 0x07c88000
BOARD_SECOND_OFFSET := 0xc0008000
BOARD_DTB_OFFSET := 0x07c88000
BOARD_DTB_SIZE := 463787

# DTBO
BOARD_PREBUILT_DTBOIMAGE := $(DEVICE_PATH)/prebuilt/dtbo.img
BOARD_DTBOIMG_PARTITION_SIZE := 451454

# Recovery
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery.fstab
BOARD_INCLUDE_RECOVERY_DTBO := true
FLASH_IMAGE_TARGET := $(PRODUCT_OUT)/recovery.tar
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 83886080
BOARD_MKBOOTIMG_ARGS := --base 0x3fff8000 --pagesize 4096 --kernel_offset 0x00008000 --ramdisk_offset 0x26f08000 --tags_offset 0x07c88000 --second_offset 0xc0008000
BOARD_AVB_RECOVERY_ALGORITHM := SHA256_RSA4096
BOARD_AVB_RECOVERY_KEY_PATH := external/avb/test/data/testkey_rsa4096.pem
BOARD_AVB_ENABLE := true
BOARD_AVB_VBMETA_SYSTEM := vbmeta_system
BOARD_AVB_VBMETA_VENDOR := vbmeta_vendor

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := cortex-a55

# Platform
TARGET_BOARD_PLATFORM := mt6989

# TWRP
TW_THEME := portrait_hdpi
TW_EXTRA_LANGUAGES := true
TW_SCREEN_BLANK_ON_BOOT := true
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
RECOVERY_SDCARD_ON_DATA := true
TW_NO_USB_STORAGE := true
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_FBE := true
TW_USE_FSCRYPT_POLICY := 1
TW_DEVICE_VERSION := 3.7.0_14-0
TW_BRIGHTNESS_PATH := /sys/class/leds/lcd-backlight/brightness
TW_MAX_BRIGHTNESS := 255
TW_DEFAULT_BRIGHTNESS := 80
TW_CRYPTO_USE_SYSTEM_VOLD := true
TW_INCLUDE_FBE_METADATA := true
